In [1]:
import pandas as pd
import statistics as stat
import matplotlib.pyplot as plt
import numpy as np

In [2]:
BMD_output = pd.read_csv('../data/input/EUT046_sciensano/BMD_output_normalized_counts_final.txt', sep='\t', skiprows=0)

In [3]:
BMD_output

,Unnamed: 0,Analysis,entrez_id,Entrez Gene IDs,Genes Symbols,Power BMD,Power BMDL,Power BMDU,Power fitPValue,Power fitLogLikelihood,...,FC Dose Level 2,FC Dose Level 3,FC Dose Level 4,FC Dose Level 5,FC Dose Level 6,FC Dose Level 7,FC Dose Level 8,FC Dose Level 9,gene_symbol,gene_symbol_entrez_id
0,0,EUT046_RODAFpreproccessed_log2normalized72h_fo...,9,NaN,NaN,16.55840,12.09740,26.06100,2.512216e-03,3.223572,...,-1.099952,1.090602,-1.363670,1.678511,1.491966,2.088251,2.640524,2.365705,NAT1,NAT1_9
1,3,EUT046_RODAFpreproccessed_log2normalized72h_fo...,12,NaN,NaN,10.25480,8.00761,14.11460,1.138656e-10,-4.705328,...,1.015930,1.030262,1.015930,-1.095391,3.142596,7.968332,5.886075,6.571031,SERPINA3,SERPINA3_12
2,4,EUT046_RODAFpreproccessed_log2normalized72h_fo...,14,NaN,NaN,13.14950,9.97040,19.35260,3.521747e-05,21.618462,...,-1.039954,1.072310,-1.151078,1.483203,1.724956,1.740706,1.552306,2.343585,AAMP,AAMP_14
3,5,EUT046_RODAFpreproccessed_log2normalized72h_fo...,16,NaN,NaN,6.75652,5.43832,9.18367,1.830667e-03,14.231372,...,-1.202582,-1.290396,1.020165,-1.418654,-1.426161,-3.190962,-5.042597,-6.472787,AARS1,AARS1_16
4,6,EUT046_RODAFpreproccessed_log2normalized72h_fo...,18,NaN,NaN,22.49870,15.37350,41.72940,7.523983e-04,-21.130428,...,-1.044462,-1.407836,-2.165387,-4.200769,-3.910782,-4.416578,-4.968928,-4.968928,ABAT,ABAT_18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24755,28184,EUT046_RODAFpreproccessed_log2normalized4h_for...,647135,NaN,NaN,18.09530,12.84340,29.81150,4.426037e-02,17.243272,...,1.259710,-1.117319,1.163996,1.160224,-1.284642,-1.336992,-1.416280,-1.742372,SRGAP2B,SRGAP2B_647135
24756,28186,EUT046_RODAFpreproccessed_log2normalized4h_for...,653519,NaN,NaN,38.87360,22.07930,135.24300,8.408922e-09,12.068372,...,1.499894,1.178187,2.499166,1.230577,-1.037138,1.153515,1.102748,-1.129618,GPR89A,GPR89A_653519
24757,28187,EUT046_RODAFpreproccessed_log2normalized4h_for...,728239,NaN,NaN,39.07710,22.20020,144.47100,5.228107e-10,6.351272,...,-1.195969,-1.110186,-3.080071,-1.163117,1.106224,1.008388,1.018247,1.231442,MAGED4,MAGED4_728239
24758,28188,EUT046_RODAFpreproccessed_log2normalized4h_for...,729092,NaN,NaN,31.93000,19.65970,84.61880,3.297568e-03,-16.039228,...,-1.008012,2.668431,-1.193450,2.965527,2.521502,2.400830,1.727351,3.788946,AGAP5,AGAP5_729092
24759,28189,EUT046_RODAFpreproccessed_log2normalized4h_for...,729288,NaN,NaN,46.77690,30.28230,47.94930,1.880382e-01,0.924772,...,-1.503945,-1.615528,-1.680402,-1.266540,-1.097658,-1.179041,-1.343052,3.022061,ZNF286B,ZNF286B_729288

In [4]:


BMD_output['Best fitPValue'] = BMD_output['Best fitPValue'].astype(float)
BMD_output['Best BMD'] = BMD_output['Best BMD'].astype(float)
BMD_output['Best BMD/BMDL'] = BMD_output['Best BMD/BMDL'].astype(float)
BMD_output['Best BMDU/BMDL'] = BMD_output['Best BMDU/BMDL'].astype(float)
BMD_output['Best RSquared'] = BMD_output['Best RSquared'].astype(float)

In [5]:
#BMD_output_filtered = BMD_output[(BMD_output['Best BMD'] <= 50) & (BMD_output['Best BMD/BMDL'] <= 20) & (BMD_output['Best BMDU/BMDL'] <= 40)]

In [6]:
# & (BMD_output['Best RSquared'] >= 0.5)

In [7]:
BMD_output_filtered = BMD_output[(BMD_output['Best BMD'] <= 50) & (BMD_output['Best BMD/BMDL'] < 20) & (BMD_output['Best BMDU/BMDL'] < 40) & (BMD_output['Best RSquared'] >= 0.8)]

In [8]:
(BMD_output_filtered['Best BMD'])

0         6.24177
1         8.97393
2         4.70880
3         8.27403
4         1.29629
           ...
24669     9.58073
24685    20.01780
24703    10.33760
24726     5.12424
24759    46.77690
Name: Best BMD, Length: 13061, dtype: float64

In [9]:
#BMD_output_filtered.to_csv('../data/input/EUT046_sciensano/BMD_output_normalized_counts_filtered.txt', sep='\t', index=False)

In [10]:
BMD_output_filtered

,Unnamed: 0,Analysis,entrez_id,Entrez Gene IDs,Genes Symbols,Power BMD,Power BMDL,Power BMDU,Power fitPValue,Power fitLogLikelihood,...,FC Dose Level 2,FC Dose Level 3,FC Dose Level 4,FC Dose Level 5,FC Dose Level 6,FC Dose Level 7,FC Dose Level 8,FC Dose Level 9,gene_symbol,gene_symbol_entrez_id
0,0,EUT046_RODAFpreproccessed_log2normalized72h_fo...,9,NaN,NaN,16.55840,12.09740,26.06100,2.512216e-03,3.223572,...,-1.099952,1.090602,-1.363670,1.678511,1.491966,2.088251,2.640524,2.365705,NAT1,NAT1_9
1,3,EUT046_RODAFpreproccessed_log2normalized72h_fo...,12,NaN,NaN,10.25480,8.00761,14.11460,1.138656e-10,-4.705328,...,1.015930,1.030262,1.015930,-1.095391,3.142596,7.968332,5.886075,6.571031,SERPINA3,SERPINA3_12
2,4,EUT046_RODAFpreproccessed_log2normalized72h_fo...,14,NaN,NaN,13.14950,9.97040,19.35260,3.521747e-05,21.618462,...,-1.039954,1.072310,-1.151078,1.483203,1.724956,1.740706,1.552306,2.343585,AAMP,AAMP_14
3,5,EUT046_RODAFpreproccessed_log2normalized72h_fo...,16,NaN,NaN,6.75652,5.43832,9.18367,1.830667e-03,14.231372,...,-1.202582,-1.290396,1.020165,-1.418654,-1.426161,-3.190962,-5.042597,-6.472787,AARS1,AARS1_16
4,6,EUT046_RODAFpreproccessed_log2normalized72h_fo...,18,NaN,NaN,22.49870,15.37350,41.72940,7.523983e-04,-21.130428,...,-1.044462,-1.407836,-2.165387,-4.200769,-3.910782,-4.416578,-4.968928,-4.968928,ABAT,ABAT_18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24669,28089,EUT046_RODAFpreproccessed_log2normalized4h_for...,116154,NaN,NaN,10.02910,7.84840,13.99310,8.619570e-04,25.492692,...,1.019807,-1.219638,-1.067905,-1.141363,-1.328675,-1.729552,-2.588375,-2.289284,PHACTR3,PHACTR3_116154
24685,28105,EUT046_RODAFpreproccessed_log2normalized4h_for...,143187,NaN,NaN,20.85620,14.51810,36.83250,3.155436e-02,28.304162,...,-1.088215,1.058654,-1.063601,1.024669,1.025602,-1.164633,-1.584153,-1.353414,VTI1A,VTI1A_143187
24703,28123,EUT046_RODAFpreproccessed_log2normalized4h_for...,160335,NaN,NaN,11.60600,8.11772,19.19330,3.622582e-04,9.759672,...,1.476267,1.104336,1.459607,1.844915,-1.173461,-1.618138,-1.968383,-3.360711,TMTC2,TMTC2_160335
24726,28152,EUT046_RODAFpreproccessed_log2normalized4h_for...,222255,NaN,NaN,8.85153,7.00152,12.46120,1.832516e-02,18.166572,...,-1.085853,-1.047460,1.136117,-1.055941,-1.684529,-1.885020,-2.877246,-3.352595,ATXN7L1,ATXN7L1_222255
24759,28189,EUT046_RODAFpreproccessed_log2normalized4h_for...,729288,NaN,NaN,46.77690,30.28230,47.94930,1.880382e-01,0.924772,...,-1.503945,-1.615528,-1.680402,-1.266540,-1.097658,-1.179041,-1.343052,3.022061,ZNF286B,ZNF286B_729288

In [11]:
BMD_output[BMD_output['Analysis'].str.contains('d4h')]

,Unnamed: 0,Analysis,entrez_id,Entrez Gene IDs,Genes Symbols,Power BMD,Power BMDL,Power BMDU,Power fitPValue,Power fitLogLikelihood,...,FC Dose Level 2,FC Dose Level 3,FC Dose Level 4,FC Dose Level 5,FC Dose Level 6,FC Dose Level 7,FC Dose Level 8,FC Dose Level 9,gene_symbol,gene_symbol_entrez_id
24111,27448,EUT046_RODAFpreproccessed_log2normalized4h_for...,9,NaN,NaN,39.0556,22.1393,118.2270,9.821843e-06,16.136772,...,1.234890,1.405874,1.502207,-1.242675,1.159043,1.537924,1.405515,1.697522,NAT1,NAT1_9
24112,27451,EUT046_RODAFpreproccessed_log2normalized4h_for...,133,NaN,NaN,18.6924,13.3336,31.0802,1.490667e-02,2.067172,...,1.113289,1.353794,-1.352040,1.029523,2.059616,1.955649,2.306839,2.654715,ADM,ADM_133
24113,27453,EUT046_RODAFpreproccessed_log2normalized4h_for...,230,NaN,NaN,62.1651,28.7025,NaN,5.549636e-05,-19.648528,...,2.015332,2.655801,3.456907,3.594004,3.915711,3.639918,1.403490,3.308293,ALDOC,ALDOC_230
24114,27454,EUT046_RODAFpreproccessed_log2normalized4h_for...,323,NaN,NaN,33.5262,20.6765,48.5210,3.771291e-02,12.078172,...,-1.019718,-1.161555,-1.331105,1.442763,-1.017486,-1.146694,-1.246673,-2.131720,APBB2,APBB2_323
24115,27455,EUT046_RODAFpreproccessed_log2normalized4h_for...,374,NaN,NaN,23.2698,14.2454,38.5554,5.905406e-03,13.204872,...,1.177152,-1.018307,-1.474421,-1.133064,1.329249,1.418002,1.308065,2.088244,AREG,AREG_374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24755,28184,EUT046_RODAFpreproccessed_log2normalized4h_for...,647135,NaN,NaN,18.0953,12.8434,29.8115,4.426037e-02,17.243272,...,1.259710,-1.117319,1.163996,1.160224,-1.284642,-1.336992,-1.416280,-1.742372,SRGAP2B,SRGAP2B_647135
24756,28186,EUT046_RODAFpreproccessed_log2normalized4h_for...,653519,NaN,NaN,38.8736,22.0793,135.2430,8.408922e-09,12.068372,...,1.499894,1.178187,2.499166,1.230577,-1.037138,1.153515,1.102748,-1.129618,GPR89A,GPR89A_653519
24757,28187,EUT046_RODAFpreproccessed_log2normalized4h_for...,728239,NaN,NaN,39.0771,22.2002,144.4710,5.228107e-10,6.351272,...,-1.195969,-1.110186,-3.080071,-1.163117,1.106224,1.008388,1.018247,1.231442,MAGED4,MAGED4_728239
24758,28188,EUT046_RODAFpreproccessed_log2normalized4h_for...,729092,NaN,NaN,31.9300,19.6597,84.6188,3.297568e-03,-16.039228,...,-1.008012,2.668431,-1.193450,2.965527,2.521502,2.400830,1.727351,3.788946,AGAP5,AGAP5_729092
24759,28189,EUT046_RODAFpreproccessed_log2normalized4h_for...,729288,NaN,NaN,46.7769,30.2823,47.9493,1.880382e-01,0.924772,...,-1.503945,-1.615528,-1.680402,-1.266540,-1.097658,-1.179041,-1.343052,3.022061,ZNF286B,ZNF286B_729288

In [12]:
multindex_l = set(BMD_output_filtered.Analysis)

In [13]:
EUT046_BMDExpress = BMD_output_filtered

In [14]:
res_d = {i:EUT046_BMDExpress[EUT046_BMDExpress.Analysis == i] for i in multindex_l}

In [15]:
biomarkers = pd.read_csv('../datasets/biomarkers_genomark_tgxddi.txt', sep='\t')

In [16]:
pathway = pd.read_csv('../data/input/EUT046_sciensano/pathway_overview.txt', sep='\t')

In [17]:
pathway[pathway.pathway == 'TGxDDI64']

       pathway  entrez_id gene_symbol gene_symbol_entrez_id
7407  TGxDDI64         59       ACTA2              ACTA2_59
7408  TGxDDI64      64782         AEN             AEN_64782
7409  TGxDDI64      10678      B3GNT2          B3GNT2_10678
7410  TGxDDI64     282991     BLOC1S2        BLOC1S2_282991
7411  TGxDDI64      84312      BRMS1L          BRMS1L_84312
...        ...        ...         ...                   ...
7466  TGxDDI64      10346      TRIM22          TRIM22_10346
7467  TGxDDI64     373856         NaN                   NaN
7468  TGxDDI64      91947      ARRDC4          ARRDC4_91947
7469  TGxDDI64       6407       SEMG2            SEMG2_6407
7470  TGxDDI64       5100       PCDH8            PCDH8_5100

[64 rows x 4 columns]

In [18]:
Analysis = []
pathwayname = []
amountgenes = []
medians = []
mediansBMDL = []
mediansBMDU = []
i = 0
for e in set(pathway.pathway):
    res_d_pathway = dict()
    #print(e)
    i += 1
    #print(i)
    for res in res_d.keys():
        res_pathway = pd.merge(pathway[pathway.pathway == e], res_d[res], how='inner', on='entrez_id')
        if len(res_pathway[['Best BMD']]) > 0: 
            Analysis.append(res)
            pathwayname.append(e)
            amountgenes.append(len(res_pathway.entrez_id))
            medians.append(stat.median(res_pathway['Best BMD']))
            mediansBMDL.append(stat.median(res_pathway['Best BMDL']))
            mediansBMDU.append(stat.median(res_pathway['Best BMDU']))
            
median_df = pd.DataFrame({'Analysis':Analysis, 'Pathway.Name':pathwayname, 'Genes.That.Passed.All.Filters':amountgenes, 'Median':medians, 'BMDL.Median':mediansBMDL, 'BMDU.Median':mediansBMDU})

In [27]:
set(pathway.pathway.to_list())

{'GENOMARK84',
 'HALLMARK_ADIPOGENESIS',
 'HALLMARK_ALLOGRAFT_REJECTION',
 'HALLMARK_ANDROGEN_RESPONSE',
 'HALLMARK_ANGIOGENESIS',
 'HALLMARK_APICAL_JUNCTION',
 'HALLMARK_APICAL_SURFACE',
 'HALLMARK_APOPTOSIS',
 'HALLMARK_BILE_ACID_METABOLISM',
 'HALLMARK_CHOLESTEROL_HOMEOSTASIS',
 'HALLMARK_COAGULATION',
 'HALLMARK_COMPLEMENT',
 'HALLMARK_DNA_REPAIR',
 'HALLMARK_E2F_TARGETS',
 'HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION',
 'HALLMARK_ESTROGEN_RESPONSE_EARLY',
 'HALLMARK_ESTROGEN_RESPONSE_LATE',
 'HALLMARK_FATTY_ACID_METABOLISM',
 'HALLMARK_G2M_CHECKPOINT',
 'HALLMARK_GLYCOLYSIS',
 'HALLMARK_HEDGEHOG_SIGNALING',
 'HALLMARK_HEME_METABOLISM',
 'HALLMARK_HYPOXIA',
 'HALLMARK_IL2_STAT5_SIGNALING',
 'HALLMARK_IL6_JAK_STAT3_SIGNALING',
 'HALLMARK_INFLAMMATORY_RESPONSE',
 'HALLMARK_INTERFERON_ALPHA_RESPONSE',
 'HALLMARK_INTERFERON_GAMMA_RESPONSE',
 'HALLMARK_KRAS_SIGNALING_DN',
 'HALLMARK_KRAS_SIGNALING_UP',
 'HALLMARK_MITOTIC_SPINDLE',
 'HALLMARK_MTORC1_SIGNALING',
 'HALLMARK_MYC_TARGETS_V1',
 'HALLMARK_MYC_TARGETS_V2',
 'HALLMARK_MYOGENESIS',
 'HALLMARK_NOTCH_SIGNALING',
 'HALLMARK_OXIDATIVE_PHOSPHORYLATION',
 'HALLMARK_P53_PATHWAY',
 'HALLMARK_PANCREAS_BETA_CELLS',
 'HALLMARK_PEROXISOME',
 'HALLMARK_PI3K_AKT_MTOR_SIGNALING',
 'HALLMARK_PROTEIN_SECRETION',
 'HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY',
 'HALLMARK_SPERMATOGENESIS',
 'HALLMARK_TGF_BETA_SIGNALING',
 'HALLMARK_TNFA_SIGNALING_VIA_NFKB',
 'HALLMARK_UNFOLDED_PROTEIN_RESPONSE',
 'HALLMARK_UV_RESPONSE_DN',
 'HALLMARK_UV_RESPONSE_UP',
 'HALLMARK_WNT_BETA_CATENIN_SIGNALING',
 'HALLMARK_XENOBIOTIC_METABOLISM',
 'TGxDDI64'}

In [34]:
median_df[median_df['Pathway.Name'] == 'HALLMARK_APOPTOSIS']

,Analysis,Pathway.Name,Genes.That.Passed.All.Filters,Median,BMDL.Median,BMDU.Median
154,EUT046_RODAFpreproccessed_log2normalized16h_fo...,HALLMARK_APOPTOSIS,25,11.740400,9.032950,17.990200
155,EUT046_RODAFpreproccessed_log2normalized72h_fo...,HALLMARK_APOPTOSIS,62,5.772415,4.182265,8.228910
156,EUT046_RODAFpreproccessed_log2normalized24h_fo...,HALLMARK_APOPTOSIS,45,9.770000,6.248780,16.710400
157,EUT046_RODAFpreproccessed_log2normalized48h_fo...,HALLMARK_APOPTOSIS,60,5.269805,3.819140,7.832285
158,EUT046_RODAFpreproccessed_log2normalized8h_for...,HALLMARK_APOPTOSIS,10,9.867995,7.734075,13.489750

In [20]:
median_df[median_df['Pathway.Name'] == 'HALLMARK_P53_PATHWAY']

,Analysis,Pathway.Name,Genes.That.Passed.All.Filters,Median,BMDL.Median,BMDU.Median
42,EUT046_RODAFpreproccessed_log2normalized16h_fo...,HALLMARK_P53_PATHWAY,46,11.19440,8.434370,17.609750
43,EUT046_RODAFpreproccessed_log2normalized72h_fo...,HALLMARK_P53_PATHWAY,94,5.90570,4.052005,9.386815
44,EUT046_RODAFpreproccessed_log2normalized24h_fo...,HALLMARK_P53_PATHWAY,67,9.20781,6.315200,14.279200
45,EUT046_RODAFpreproccessed_log2normalized48h_fo...,HALLMARK_P53_PATHWAY,85,4.35679,2.760710,6.295710
46,EUT046_RODAFpreproccessed_log2normalized8h_for...,HALLMARK_P53_PATHWAY,17,10.80240,8.389600,15.214300
47,EUT046_RODAFpreproccessed_log2normalized4h_for...,HALLMARK_P53_PATHWAY,1,15.25110,11.305000,23.266300

In [21]:
#median_df.to_csv('../data/input/EUT046_sciensano/medianBMD_pathways_normalized_counts_finalfiltered.txt', sep='\t', index=False)

In [37]:
NES_BMD_output = pd.read_csv('../data/input/EUT046_sciensano/BMD_output_NES_final.txt', sep='\t')

In [52]:
NES_BMD_output[['Analysis', 'pathway', 'Best BMD']][(NES_BMD_output.pathway == 'GENOMARK84') | (NES_BMD_output.pathway == 'TGxDDI64')]

               Analysis     pathway   Best BMD
0    EUT046_NES_72h_BMD  GENOMARK84   6.904040
51   EUT046_NES_72h_BMD    TGxDDI64   0.174378
52   EUT046_NES_48h_BMD  GENOMARK84   0.426852
103  EUT046_NES_48h_BMD    TGxDDI64   0.521687
104  EUT046_NES_24h_BMD  GENOMARK84   0.143489
155  EUT046_NES_24h_BMD    TGxDDI64   6.958200
156  EUT046_NES_16h_BMD  GENOMARK84  10.046700
207  EUT046_NES_16h_BMD    TGxDDI64  22.502200
208   EUT046_NES_8h_BMD  GENOMARK84  50.980100
259   EUT046_NES_8h_BMD    TGxDDI64   6.776890
260   EUT046_NES_4h_BMD  GENOMARK84  32.139900
311   EUT046_NES_4h_BMD    TGxDDI64  23.811300