In [1]:
import pandas as pd
import numpy as np

In [2]:
EUT046_normalized = pd.read_csv('../datasets/EUT046_RODAFpreprocessed_normalizedcounts.csv', index_col='Unnamed: 0')

In [3]:
EUT046_normalized.replace(0, 1, inplace=True)

In [4]:
EUT046_log2normalized = np.log2(EUT046_normalized)

In [5]:
EUT046_log2normalized

,S_4h_Cis9_Rep1,S_4h_Cis9_Rep2,S_4h_Cis9_Rep3,S_4h_Cis8_Rep1,S_4h_Cis8_Rep2,S_4h_Cis8_Rep3,S_4h_Cis7_Rep1,S_4h_Cis7_Rep2,S_4h_Cis7_Rep3,S_4h_Cis6_Rep1,...,S_48h_DMEM_Rep3,S_48h_DMEM_Rep4,S_48h_DMEM_Rep5,S_48h_DMEM_Rep6,S_72h_DMEM_Rep1,S_72h_DMEM_Rep2,S_72h_DMEM_Rep3,S_72h_DMEM_Rep4,S_72h_DMEM_Rep5,S_72h_DMEM_Rep6
A2M_2,-0.388387,1.948361,1.065905,1.895774,0.016629,0.000000,1.690129,-0.373990,2.115714,-0.480271,...,1.264541,2.038546,1.226546,1.213379,1.604846,0.000000,1.115987,0.000000,0.000000,-0.136840
A4GALT_53947,6.021004,6.098108,6.503310,6.288091,6.264557,6.468294,6.149560,5.815834,6.437642,5.649012,...,6.171432,6.440645,6.601585,6.553229,4.412201,2.712460,4.115987,4.386815,4.311981,4.255478
AAAS_8086,3.071044,3.118286,2.802871,3.355206,3.338557,2.062301,3.390568,2.947938,2.378748,1.841657,...,2.679578,3.038546,3.685978,1.798341,3.341812,2.849963,2.437915,0.000000,3.418897,3.185088
AACS_65985,4.859540,3.948361,3.802871,4.849970,4.660485,3.547728,4.899582,4.835463,4.317347,2.519729,...,5.001507,4.959112,4.314009,4.798341,4.479315,4.519815,4.639549,3.912884,4.366429,4.907554
AAGAB_79719,9.861911,9.815640,9.866805,9.847059,9.833613,9.642748,9.348340,9.746248,9.753787,10.254438,...,9.655426,9.215610,9.575274,9.736941,9.497642,9.363511,9.655146,9.915386,9.936847,9.457485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11A_440590,4.366500,3.855251,4.972796,4.065699,4.264557,3.647264,4.012057,4.085441,4.115714,5.542096,...,5.037130,5.297281,4.548474,4.672810,5.634594,4.390532,4.363915,4.990886,4.255398,4.111088
ZYG11B_79699,2.418968,2.755716,2.650867,-0.104226,2.601592,2.740373,3.390568,2.626010,3.115714,2.689654,...,3.380018,2.553120,2.548474,4.020734,3.341812,2.560457,2.700950,0.000000,3.699005,2.670515
ZYX_7791,9.574509,9.424094,9.512988,9.798149,9.730875,9.356922,9.523019,9.756580,9.599529,9.282941,...,8.811435,9.030473,8.788788,8.672810,9.136228,8.902284,8.958337,8.848867,8.871285,8.696050
ZZEF1_23140,3.518503,4.035824,4.181382,3.596214,3.338557,4.827836,3.860054,3.626010,3.700676,5.473925,...,3.380018,4.360474,4.033901,4.383304,4.774771,3.638459,4.115987,4.697155,4.740825,4.448123
ZZZ3_26009,0.000000,1.948361,-0.519058,2.217702,2.338557,2.740373,2.497484,1.210972,1.378748,1.519729,...,-0.320422,1.816154,2.226546,1.213379,1.604846,2.712460,1.700950,0.742959,2.196504,1.863160

In [6]:
EUT046_normalized.reset_index(drop=False, inplace=True)

In [7]:
EUT046_log2normalized.reset_index(drop=False, inplace=True)

In [8]:
EUT046_normalized = EUT046_normalized.rename(columns={'index': '0_0_Dose'})

In [9]:
EUT046_log2normalized = EUT046_log2normalized.rename(columns={'index': '0_0_Dose'})

In [10]:
EUT046_log2normalized

,0_0_Dose,S_4h_Cis9_Rep1,S_4h_Cis9_Rep2,S_4h_Cis9_Rep3,S_4h_Cis8_Rep1,S_4h_Cis8_Rep2,S_4h_Cis8_Rep3,S_4h_Cis7_Rep1,S_4h_Cis7_Rep2,S_4h_Cis7_Rep3,...,S_48h_DMEM_Rep3,S_48h_DMEM_Rep4,S_48h_DMEM_Rep5,S_48h_DMEM_Rep6,S_72h_DMEM_Rep1,S_72h_DMEM_Rep2,S_72h_DMEM_Rep3,S_72h_DMEM_Rep4,S_72h_DMEM_Rep5,S_72h_DMEM_Rep6
0,A2M_2,-0.388387,1.948361,1.065905,1.895774,0.016629,0.000000,1.690129,-0.373990,2.115714,...,1.264541,2.038546,1.226546,1.213379,1.604846,0.000000,1.115987,0.000000,0.000000,-0.136840
1,A4GALT_53947,6.021004,6.098108,6.503310,6.288091,6.264557,6.468294,6.149560,5.815834,6.437642,...,6.171432,6.440645,6.601585,6.553229,4.412201,2.712460,4.115987,4.386815,4.311981,4.255478
2,AAAS_8086,3.071044,3.118286,2.802871,3.355206,3.338557,2.062301,3.390568,2.947938,2.378748,...,2.679578,3.038546,3.685978,1.798341,3.341812,2.849963,2.437915,0.000000,3.418897,3.185088
3,AACS_65985,4.859540,3.948361,3.802871,4.849970,4.660485,3.547728,4.899582,4.835463,4.317347,...,5.001507,4.959112,4.314009,4.798341,4.479315,4.519815,4.639549,3.912884,4.366429,4.907554
4,AAGAB_79719,9.861911,9.815640,9.866805,9.847059,9.833613,9.642748,9.348340,9.746248,9.753787,...,9.655426,9.215610,9.575274,9.736941,9.497642,9.363511,9.655146,9.915386,9.936847,9.457485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11527,ZYG11A_440590,4.366500,3.855251,4.972796,4.065699,4.264557,3.647264,4.012057,4.085441,4.115714,...,5.037130,5.297281,4.548474,4.672810,5.634594,4.390532,4.363915,4.990886,4.255398,4.111088
11528,ZYG11B_79699,2.418968,2.755716,2.650867,-0.104226,2.601592,2.740373,3.390568,2.626010,3.115714,...,3.380018,2.553120,2.548474,4.020734,3.341812,2.560457,2.700950,0.000000,3.699005,2.670515
11529,ZYX_7791,9.574509,9.424094,9.512988,9.798149,9.730875,9.356922,9.523019,9.756580,9.599529,...,8.811435,9.030473,8.788788,8.672810,9.136228,8.902284,8.958337,8.848867,8.871285,8.696050
11530,ZZEF1_23140,3.518503,4.035824,4.181382,3.596214,3.338557,4.827836,3.860054,3.626010,3.700676,...,3.380018,4.360474,4.033901,4.383304,4.774771,3.638459,4.115987,4.697155,4.740825,4.448123
11531,ZZZ3_26009,0.000000,1.948361,-0.519058,2.217702,2.338557,2.740373,2.497484,1.210972,1.378748,...,-0.320422,1.816154,2.226546,1.213379,1.604846,2.712460,1.700950,0.742959,2.196504,1.863160

In [11]:
EUT046_normalized = pd.concat([EUT046_normalized,pd.DataFrame({col:col.split('_')[2] for col in EUT046_normalized.columns}, index=[1])])

In [12]:
EUT046_log2normalized = pd.concat([EUT046_log2normalized,pd.DataFrame({col:col.split('_')[2] for col in EUT046_log2normalized.columns}, index=[1])])

In [13]:
conc = {'DMEM':0, 'Cis9':0.01, 'Cis8':0.5, 'Cis7':1, 'Cis6':2.5, 'Cis5':5, 'Cis4':10, 'Cis3':20, 'Cis2':30, 'Cis1':50}

In [14]:
EUT046_normalized = EUT046_normalized.replace(conc)

In [15]:
EUT046_log2normalized = EUT046_log2normalized.replace(conc)

In [16]:
derniere_ligne = EUT046_normalized.iloc[-1]
EUT046_normalized = pd.concat([derniere_ligne.to_frame().T, EUT046_normalized.iloc[:-1]])

In [17]:
derniere_ligne = EUT046_log2normalized.iloc[-1]
EUT046_log2normalized = pd.concat([derniere_ligne.to_frame().T, EUT046_log2normalized.iloc[:-1]])

In [18]:
EUT046_normalized.reset_index(drop=True, inplace=True)

In [19]:
EUT046_log2normalized.reset_index(drop=True, inplace=True)

In [20]:
EUT046_log2normalized

,0_0_Dose,S_4h_Cis9_Rep1,S_4h_Cis9_Rep2,S_4h_Cis9_Rep3,S_4h_Cis8_Rep1,S_4h_Cis8_Rep2,S_4h_Cis8_Rep3,S_4h_Cis7_Rep1,S_4h_Cis7_Rep2,S_4h_Cis7_Rep3,...,S_48h_DMEM_Rep3,S_48h_DMEM_Rep4,S_48h_DMEM_Rep5,S_48h_DMEM_Rep6,S_72h_DMEM_Rep1,S_72h_DMEM_Rep2,S_72h_DMEM_Rep3,S_72h_DMEM_Rep4,S_72h_DMEM_Rep5,S_72h_DMEM_Rep6
0,Dose,0.01,0.01,0.01,0.5,0.5,0.5,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,A2M_2,-0.388387,1.948361,1.065905,1.895774,0.016629,0.0,1.690129,-0.37399,2.115714,...,1.264541,2.038546,1.226546,1.213379,1.604846,0.0,1.115987,0.0,0.0,-0.13684
2,A4GALT_53947,6.021004,6.098108,6.50331,6.288091,6.264557,6.468294,6.14956,5.815834,6.437642,...,6.171432,6.440645,6.601585,6.553229,4.412201,2.71246,4.115987,4.386815,4.311981,4.255478
3,AAAS_8086,3.071044,3.118286,2.802871,3.355206,3.338557,2.062301,3.390568,2.947938,2.378748,...,2.679578,3.038546,3.685978,1.798341,3.341812,2.849963,2.437915,0.0,3.418897,3.185088
4,AACS_65985,4.85954,3.948361,3.802871,4.84997,4.660485,3.547728,4.899582,4.835463,4.317347,...,5.001507,4.959112,4.314009,4.798341,4.479315,4.519815,4.639549,3.912884,4.366429,4.907554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11528,ZYG11A_440590,4.3665,3.855251,4.972796,4.065699,4.264557,3.647264,4.012057,4.085441,4.115714,...,5.03713,5.297281,4.548474,4.67281,5.634594,4.390532,4.363915,4.990886,4.255398,4.111088
11529,ZYG11B_79699,2.418968,2.755716,2.650867,-0.104226,2.601592,2.740373,3.390568,2.62601,3.115714,...,3.380018,2.55312,2.548474,4.020734,3.341812,2.560457,2.70095,0.0,3.699005,2.670515
11530,ZYX_7791,9.574509,9.424094,9.512988,9.798149,9.730875,9.356922,9.523019,9.75658,9.599529,...,8.811435,9.030473,8.788788,8.67281,9.136228,8.902284,8.958337,8.848867,8.871285,8.69605
11531,ZZEF1_23140,3.518503,4.035824,4.181382,3.596214,3.338557,4.827836,3.860054,3.62601,3.700676,...,3.380018,4.360474,4.033901,4.383304,4.774771,3.638459,4.115987,4.697155,4.740825,4.448123
11532,ZZZ3_26009,0.0,1.948361,-0.519058,2.217702,2.338557,2.740373,2.497484,1.210972,1.378748,...,-0.320422,1.816154,2.226546,1.213379,1.604846,2.71246,1.70095,0.742959,2.196504,1.86316

In [21]:
timepoint_l = ['4h', '8h', '16h', '24h', '48h', '72h']
timepoint_d = dict()
for timepoint in timepoint_l:
    key1 = f'EUT046_RODAFpreprocessed_normalized{timepoint}'
    value1 = EUT046_normalized.filter(regex=f'_{timepoint}_|Dose')
    timepoint_d[key1] = value1

for k,v in timepoint_d.items():  
    
    v.to_csv(f'../datasets/EUT046_RODAF_preproccessed_forBMD/{k}_forBMDExpress.txt', sep='\t', index=False)