In [1]:
import pandas as pd
import re

In [2]:
EUT046 = pd.read_csv('../datasets/EUT046_counts_per_gene_per_sample_raw_final.csv')
EUT046_manifest = pd.read_table('../datasets/Temposeq_manifest_Human_WT_1.2_realignment_96percent_2023-05-15 (1).txt')

In [3]:
EUT046_manifest

,Probe_ID,Gene_Symbol_TS,Probe_NR,Probe_length,Probe_sequence,Reference_Transcript,Transcripts_Targeted,gene_symbol,entrez_id,gene_symbol_entrez_id,transcript_id,database
0,A1BG_25586,A1BG,25586,50,TCAGGCACCTCCAGAAACTCATGGTCGCCCTCCCGCCTCAGCAGAA...,NM_130786,NM_130786,A1BG,1.0,A1BG_1,NM_130786,NM
1,A1CF_28946,A1CF,28946,50,GGTTGTATATGCTGCTAAGTCTTGTCCAAGGGTTACCGCTTGCTTG...,NM_001198819,NM_014576+NM_138932+NM_001198818+NM_001198820+...,A1CF,29974.0,A1CF_29974,NM_014576,NM
2,A2M_1,A2M,1,50,GAACAGGACTCCAGCAAAGCACTTTTCAGCCTTGTGGTCTTCAAGC...,NM_000014,NM_000014,A2M,2.0,A2M_2,NM_000014,NM
3,A2M_12371,A2M,12371,50,CTTCAGGTTCAACCAACAGAGGCTTGATGACTGTGTCTTTCCTTCC...,NM_000014,NM_000014,A2M,2.0,A2M_2,NM_000014,NM
4,A2ML1_18347,A2ML1,18347,50,ATGACCCTGCCCATGCAACGCCTCCTCTGAGTGATTGTTCCTATCC...,NM_144670,NM_001282424+NM_144670,A2ML1,144568.0,A2ML1_144568,NM_144670,NM
...,...,...,...,...,...,...,...,...,...,...,...,...
21106,ZYG11B_10994,ZYG11B,10994,50,TGGTTAGAGACTTGAGTCGGTCTTTGCAGGCCAGTAGAGCAGTGAT...,NM_024646,NM_024646,ZYG11B,79699.0,ZYG11B_79699,NM_024646,NM
21107,ZYX_10702,ZYX,10702,50,CCCTCCAGACTGTAGAACTGCTGGCCCTGGAGCTGCTGCGCACACT...,NM_003461,NM_003461+NM_001010972,ZYX,7791.0,ZYX_7791,NM_003461,NM
21108,ZYX_7929,ZYX,7929,50,TCATGTGGAAGTTCTTGTCCAGGGCGACCACTCGCACAGTCTCATC...,NM_003461,NM_003461+NM_001010972,ZYX,7791.0,ZYX_7791,NM_003461,NM
21109,ZZEF1_19722,ZZEF1,19722,50,TGCTCATGTCGGAGGTGAAGCGGTAATACAGAGTGTCTCCTGGAAG...,NM_015113,NM_015113,ZZEF1,23140.0,ZZEF1_23140,NM_015113,NM
21110,ZZZ3_14276,ZZZ3,14276,50,GGATCATCATCTTCCTCTTCTGTAATGTGCTGACTGGCACTCTCTT...,NM_015534,NM_015534,ZZZ3,26009.0,ZZZ3_26009,NM_015534,NM

In [4]:
EUT046_metadata = pd.read_csv('../metadata/EUT046_metadata_final (1).csv')

In [5]:
EUT046_metadata

,SAMPLE_ID,SAMPLE,PLATE_ID,LOCATION_ID,WELL_ID,PLATE_NR,EXP_ID,SPECIES,CELL_ID,TREATMENT,...,CONCENTRATION,DOSE,DOSE_LEVEL,REPLICATE,TREATMENT_ID,meanID,SAMPLENAME,LIB_SIZE,ReadDepth,VariableQCs
0,S_4h_Cis9_Rep1,Human_ RPTEC-TERT1_ CSP_ 4hr_ 0.1uM_R1,LEIDEN_TQ_RPTEC_CSP1,LEIDEN_TQ_RPTEC_CSP1_A10,A10,P1,EUT046,Human,RPTEC-TERT1,CSP,...,0.1uM,1,1,1,RPTEC-TERT1_ CSP_ 4hr_ 0.1uM,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_CSP_conc0...,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_CSP_TP4_c...,5119900,2425228554,4
1,S_4h_Cis9_Rep2,Human_ RPTEC-TERT1_ CSP_ 4hr_ 0.1uM_R2,LEIDEN_TQ_RPTEC_CSP1,LEIDEN_TQ_RPTEC_CSP1_B10,B10,P1,EUT046,Human,RPTEC-TERT1,CSP,...,0.1uM,1,1,2,RPTEC-TERT1_ CSP_ 4hr_ 0.1uM,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_CSP_conc0...,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_CSP_TP4_c...,4102283,1943196912,4
2,S_4h_Cis9_Rep3,Human_ RPTEC-TERT1_ CSP_ 4hr_ 0.1uM_R3,LEIDEN_TQ_RPTEC_CSP1,LEIDEN_TQ_RPTEC_CSP1_C10,C10,P1,EUT046,Human,RPTEC-TERT1,CSP,...,0.1uM,1,1,3,RPTEC-TERT1_ CSP_ 4hr_ 0.1uM,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_CSP_conc0...,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_CSP_TP4_c...,5076545,2404691867,4
3,S_4h_Cis8_Rep1,Human_ RPTEC-TERT1_ CSP_ 4hr_ 0.5uM_R1,LEIDEN_TQ_RPTEC_CSP1,LEIDEN_TQ_RPTEC_CSP1_A09,A09,P1,EUT046,Human,RPTEC-TERT1,CSP,...,0.5uM,5,2,1,RPTEC-TERT1_ CSP_ 4hr_ 0.5uM,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_CSP_conc0...,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_CSP_TP4_c...,4444916,2105497608,4
4,S_4h_Cis8_Rep2,Human_ RPTEC-TERT1_ CSP_ 4hr_ 0.5uM_R2,LEIDEN_TQ_RPTEC_CSP1,LEIDEN_TQ_RPTEC_CSP1_B09,B09,P1,EUT046,Human,RPTEC-TERT1,CSP,...,0.5uM,5,2,2,RPTEC-TERT1_ CSP_ 4hr_ 0.5uM,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_CSP_conc0...,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_CSP_TP4_c...,4126227,1954538866,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,S_72h_DMEM_Rep2,Human_ RPTEC-TERT1_ DMEM_ 72hr_ 0uM_R2,LEIDEN_TQ_RPTEC_CSP3,LEIDEN_TQ_RPTEC_CSP3_D12,D12,P3,EUT046,Human,RPTEC-TERT1,DMEM,...,0uM,0,0,2,RPTEC-TERT1_ DMEM_ 72hr_ 0uM,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_DMEM_conc...,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_DMEM_TP72...,4495628,2129519208,72
200,S_72h_DMEM_Rep3,Human_ RPTEC-TERT1_ DMEM_ 72hr_ 0uM_R3,LEIDEN_TQ_RPTEC_CSP3,LEIDEN_TQ_RPTEC_CSP3_E11,E11,P3,EUT046,Human,RPTEC-TERT1,DMEM,...,0uM,0,0,3,RPTEC-TERT1_ DMEM_ 72hr_ 0uM,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_DMEM_conc...,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_DMEM_TP72...,5874938,2782880015,72
201,S_72h_DMEM_Rep4,Human_ RPTEC-TERT1_ DMEM_ 72hr_ 0uM_R4,LEIDEN_TQ_RPTEC_CSP3,LEIDEN_TQ_RPTEC_CSP3_E12,E12,P3,EUT046,Human,RPTEC-TERT1,DMEM,...,0uM,0,0,4,RPTEC-TERT1_ DMEM_ 72hr_ 0uM,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_DMEM_conc...,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_DMEM_TP72...,4881679,2312386434,72
202,S_72h_DMEM_Rep5,Human_ RPTEC-TERT1_ DMEM_ 72hr_ 0uM_R5,LEIDEN_TQ_RPTEC_CSP3,LEIDEN_TQ_RPTEC_CSP3_F11,F11,P3,EUT046,Human,RPTEC-TERT1,DMEM,...,0uM,0,0,5,RPTEC-TERT1_ DMEM_ 72hr_ 0uM,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_DMEM_conc...,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_DMEM_TP72...,3524126,1669331628,72
203,S_72h_DMEM_Rep6,Human_ RPTEC-TERT1_ DMEM_ 72hr_ 0uM_R6,LEIDEN_TQ_RPTEC_CSP3,LEIDEN_TQ_RPTEC_CSP3_F12,F12,P3,EUT046,Human,RPTEC-TERT1,DMEM,...,0uM,0,0,6,RPTEC-TERT1_ DMEM_ 72hr_ 0uM,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_DMEM_conc...,Transcriptomic_CSP_RPTEC_RPTEC-TERT1_DMEM_TP72...,4493812,2128658993,72

In [6]:
libsize_df = pd.DataFrame({'SAMPLE_ID':list(EUT046.columns)[1:], 'LIB_SIZE':[sum(EUT046[c]) for c in list(EUT046.columns)[1:]]})

In [7]:
EUT046_manifest.rename(columns={'Probe_ID':'PROBE_ID'}, inplace=True)

In [8]:
EUT046.rename(columns={'Column1':'PROBE_ID'}, inplace=True)

In [9]:
def calculate_cpm_for_dataframe(df, sample_sizes_in_millions):

    cpm_df = pd.DataFrame()

    for condition, sample_size_in_millions in zip(list(df.columns)[1:], sample_sizes_in_millions):
        cpm = (df[condition] / sample_size_in_millions)
        cpm_df[condition + '_CPM'] = cpm * 1000000
        
    cpm_df = pd.concat([df['PROBE_ID'], cpm_df], axis=1)
    return cpm_df

In [10]:
EUT046_CPM = calculate_cpm_for_dataframe(EUT046, list(libsize_df.LIB_SIZE))

C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000
C:\Users\EmDe5048\AppData\Local\Temp\ipykernel_16428\633937733.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cpm_df[condition + '_CPM'] = cpm * 1000000

In [11]:
def assign_boolean(cpm_value):
    if cpm_value >= 1:
        return 1
    else:       
        return 0

In [12]:
EUT046_bool = EUT046_CPM.iloc[:,1:].applymap(assign_boolean)

In [13]:
EUT046_bool = pd.concat([EUT046.iloc[:,0], EUT046_bool], axis=1)

In [14]:
conditions = list(set([e.split('_Rep')[0] for e in EUT046_bool.iloc[:,1:].columns]))

In [15]:
def check_75_percent(row):
    # Compter le nombre de valeurs supérieures à 1 pour chaque ligne (gène)
    count_above_one = sum(row[:] >= 1)
    # Vérifier si 75% ou plus des valeurs sont supérieures à 1
    return count_above_one / len(row) >= 0.75

In [16]:
filtered_pd = EUT046_bool['PROBE_ID']
for condition in conditions:
    filtered_columns = EUT046_bool.iloc[:,1:].filter(regex=re.compile(condition))
    print(len(filtered_columns.columns))
    filtered_columns[condition] =  filtered_columns.apply(check_75_percent, axis=1)
    filtered_pd = pd.concat([filtered_pd, filtered_columns[condition]], axis=1)

3
3
6
3
3
3
6
3
3
3
3
3
3
3
3
6
3
3
3
3
3
3
3
3
3
3
3
6
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
6
3
3
3
3
3
3
6
3
6
3
3
3
3

In [17]:
preprocessed_EUT046 = filtered_pd[filtered_pd.iloc[:,1:].any(axis=1)]

In [18]:
preprocessed_EUT046_counts = pd.merge(preprocessed_EUT046[['PROBE_ID']], EUT046, how='left', on='PROBE_ID')

In [19]:
preprocessed_EUT046_to_sum = pd.merge(preprocessed_EUT046_counts, EUT046_manifest[['PROBE_ID', 'gene_symbol']], how='left', on='PROBE_ID')

In [20]:
preprocessed_EUT046_to_sum

,PROBE_ID,S_0h_DMEM_Rep1,S_0h_DMEM_Rep2,S_0h_DMEM_Rep3,S_0h_DMEM_Rep4,S_0h_DMEM_Rep5,S_0h_DMEM_Rep6,S_16h_Cis1_Rep1,S_16h_Cis1_Rep2,S_16h_Cis1_Rep3,...,S_8h_Cis9_Rep1,S_8h_Cis9_Rep2,S_8h_Cis9_Rep3,S_8h_DMEM_Rep1,S_8h_DMEM_Rep2,S_8h_DMEM_Rep3,S_8h_DMEM_Rep4,S_8h_DMEM_Rep5,S_8h_DMEM_Rep6,gene_symbol
0,NAA50_4434,2,5,4,2,3,5,2,8,2,...,2,3,2,6,9,8,0,4,1,NAA50
1,PABPN1_4895,4,3,0,3,4,4,2,9,3,...,0,7,2,3,0,1,1,0,1,PABPN1
2,TGFB3_7059,4,11,3,8,4,4,11,14,12,...,3,14,2,10,5,4,10,16,5,TGFB3
3,TMEM230_7197,254,307,480,596,380,295,392,400,315,...,54,551,362,391,332,319,451,573,229,TMEM230
4,TOP2A_7277,32,34,35,32,39,34,30,42,30,...,6,45,35,65,52,27,31,42,20,TOP2A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12629,HAP1_15262,1,2,3,1,0,0,8,1,9,...,4,3,0,1,0,0,0,2,0,HAP1
12630,MPHOSPH10_15286,467,385,337,394,429,408,696,710,609,...,397,452,503,418,695,520,704,627,369,MPHOSPH10
12631,IFT46_15294,60,46,38,54,52,60,63,73,44,...,12,29,75,43,66,48,64,46,41,IFT46
12632,CRLS1_15326,655,636,884,1162,806,664,809,1028,799,...,232,1517,1111,1105,1118,947,1325,1694,778,CRLS1
12633,FAM129B_15334,1242,1269,1216,1306,1402,1236,1460,1606,1208,...,699,1619,2145,2622,2721,2202,2476,2037,1274,NIBAN2

In [21]:
preprocessed_EUT046_sumcounts = preprocessed_EUT046_to_sum.groupby('gene_symbol', as_index=False).sum()

In [22]:
preprocessed_EUT046_sumcounts

,gene_symbol,S_0h_DMEM_Rep1,S_0h_DMEM_Rep2,S_0h_DMEM_Rep3,S_0h_DMEM_Rep4,S_0h_DMEM_Rep5,S_0h_DMEM_Rep6,S_16h_Cis1_Rep1,S_16h_Cis1_Rep2,S_16h_Cis1_Rep3,...,S_8h_Cis8_Rep3,S_8h_Cis9_Rep1,S_8h_Cis9_Rep2,S_8h_Cis9_Rep3,S_8h_DMEM_Rep1,S_8h_DMEM_Rep2,S_8h_DMEM_Rep3,S_8h_DMEM_Rep4,S_8h_DMEM_Rep5,S_8h_DMEM_Rep6
0,A2M,3,2,5,4,11,7,0,2,2,...,8,1,6,4,11,3,7,0,1,2
1,A4GALT,76,66,99,56,65,61,65,78,28,...,116,66,82,110,223,103,131,134,188,66
2,AAAS,8,20,21,19,20,20,10,15,8,...,19,1,10,17,23,17,13,11,7,0
3,AACS,26,29,31,38,43,48,11,7,11,...,28,14,32,23,54,44,52,21,26,12
4,AAGAB,749,772,954,1123,845,832,1248,1455,1390,...,1255,338,1484,1494,1353,1272,1222,1562,1615,812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11526,ZYG11A,15,13,34,38,32,16,27,33,19,...,26,53,37,24,39,20,29,42,54,22
11527,ZYG11B,6,13,25,26,24,11,12,2,11,...,22,14,22,12,20,6,9,14,5,8
11528,ZYX,452,523,515,555,573,459,717,724,655,...,757,450,846,906,1184,920,896,1031,916,532
11529,ZZEF1,11,23,12,28,26,12,8,8,1,...,24,23,34,28,24,12,22,31,18,17
11530,ZZZ3,11,7,13,10,18,8,9,3,3,...,5,3,0,8,17,5,8,11,4,3

In [23]:
#preprocessed_EUT046_sumcounts.to_csv('../datasets/EUT046_RODAFpreprocessed_sumcounts.csv', index=False)